In [1]:
%run data_gather-Copy1.ipynb

{'_type': 'album',
 'api_path': '/albums/102298',
 'cover_art_thumbnail_url': 'https://images.genius.com/dc9148a9c2eb963ae0b5564ef2042412.300x300x1.jpg',
 'cover_art_url': 'https://images.genius.com/dc9148a9c2eb963ae0b5564ef2042412.1000x1000x1.jpg',
 'full_title': 'Euphoria Mourning by Chris Cornell',
 'id': 102298,
 'name': 'Euphoria Mourning',
 'name_with_artist': 'Euphoria Mourning (artist: Chris Cornell)',
 'primary_artist_names': 'Chris Cornell',
 'pusher_channel': 'album-102298',
 'release_date_components': {'year': 1999, 'month': 9, 'day': 21},
 'release_date_for_display': 'September 21, 1999',
 'updated_at': 1739842718,
 'url': 'https://genius.com/albums/Chris-cornell/Euphoria-mourning',
 'current_user_metadata': {'permissions': ['create_comment'],
                           'excluded_permissions': ['set_album_color_gradient',
                                                    'edit',
                                                    'destroy',
                                                    'pyong',
                                                    'lock',
                                                    'super_lock',
                                                    'unlock',
                                                    'sort_songs',
                                                    'hide',
                                                    'unhide',
                                                    'see_short_id',
                                                    'create_additional_role',
                                                    'create_question'],
                           'interactions': {'pyong': False, 'following': False},
                           'iq_by_action': {}},
 'artist': 'Chris Cornell',
 'primary_artists': [{'_type': 'artist',
                      'api_path': '/artists/18435',
                      'header_image_url': 'https://images.genius.com/b6a79ad3d1aa69a9dfb83168a82022f7.473x281x1.png',
                      'id': 18435,
                      'image_url': 'https://images.genius.com/13f0e2fe12d710928b62ec5a98778cc3.1000x1000x1.jpg',
                      'index_character': 'c',
                      'is_meme_verified': False,
                      'is_verified': False,
                      'links_config': None,
                      'name': 'Chris Cornell',
                      'slug': 'Chris-cornell',
                      'url': 'https://genius.com/artists/Chris-cornell'}],
 'album_type': 'album',
 'comment_count': 0,
 'custom_header_image_url': 'https://images.genius.com/588bfe15d081baa0ae31ed59960244c0.461x251x1.png',
 'description_preview': '',
 'header_image_url': 'https://images.genius.com/588bfe15d081baa0ae31ed59960244c0.461x251x1.png',
 'hidden': False,
 'language': None,
 'lock_state': 'editable',
 'pyongs_count': 0,
 'release_date': '1999-09-21',
 'tracking_paths': {'aggregate': '/albums/Chris-cornell/Euphoria-mourning',
                    'concurrent': '/albums/Chris-cornell/Euphoria-mourning'},
 'viewable_by_roles': [],
 'album_art_primary_color': '#b7bc57',
 'album_art_secondary_color': '#a0cbd6',
 'album_art_text_color': '#000',
 'song_pageviews': 138643,
 'album_relationships': [{'_type': 'album_relationship',
                          'relationship_type': 'deluxe_edition_of',
                          'albums': []},
                         {'_type': 'album_relationship',
                          'relationship_type': 'has_deluxe_edition',
                          'albums': []},
                         {'_type': 'album_relationship',
                          'relationship_type': 'alternate_version_of',
                          'albums': []},
                         {'_type': 'album_relationship',
                          'relationship_type': 'has_alternate_version',
                          'albums': []},
                         {'_type': 'album_relationship',
                          'relationship_type': 'reissue_of',
                          'albums': []},
                         {'_type': 'album_relationship',
                          'relationship_type': 'has_reissue',
                          'albums': []},
                         {'_type': 'album_relationship',
                          'relationship_type': 'remix_version_of',
                          'albums': []},
                         {'_type': 'album_relationship',
                          'relationship_type': 'has_remix_version',
                          'albums': []}],
 'cover_arts': [{'_type': 'cover_art',
                 'annotated': False,
                 'api_path': '/albums/102298',
                 'id': 21402,
                 'image_url': 'https://images.genius.com/dc9148a9c2eb963ae0b5564ef2042412.1000x1000x1.jpg',
                 'thumbnail_image_url': 'https://images.genius.com/dc9148a9c2eb963ae0b5564ef2042412.300x300x1.jpg',
                 'url': 'https://genius.com/album_cover_arts/21402',
                 'current_user_metadata': {'permissions': [],
                                           'excluded_permissions': ['destroy']},
                 'description_annotation': {'_type': 'referent',
                                            'annotator_id': 2937273,
                                            'annotator_login': 'geniusbot',
                                            'api_path': '/referents/12001602',
                                            'classification': 'needs_exegesis',
                                            'fragment': 'https://images.genius.com/dc9148a9c2eb963ae0b5564ef2042412.1000x1000x1.jpg',
                                            'id': 12001602,
                                            'ios_app_url': 'genius://referents/12001602',
                                            'is_description': True,
                                            'is_image': True,
                                            'path': '/12001602/Euphoria-mourning/Https-imagesgeniuscom-dc9148a9c2eb963ae0b5564ef20424121000x1000x1jpg',
                                            'range': {'content': 'https://images.genius.com/dc9148a9c2eb963ae0b5564ef2042412.1000x1000x1.jpg'},
                                            'song_id': None,
                                            'url': 'https://genius.com/12001602/Euphoria-mourning/Https-imagesgeniuscom-dc9148a9c2eb963ae0b5564ef20424121000x1000x1jpg',
                                            'verified_annotator_ids': [],
                                            'current_user_metadata': {'permissions': [],
                                                                      'excluded_permissions': ['add_pinned_annotation_to',
                                                                                               'add_community_annotation_to'],
                                                                      'relationships': {}},
                                            'tracking_paths': {'aggregate': '/12001602/Euphoria-mourning/Https-imagesgeniuscom-dc9148a9c2eb963ae0b5564ef20424121000x1000x1jpg',
                                                               'concurrent': '/albums/Chris-cornell/Euphoria-mourning'},
                                            'twitter_share_message': '“?” '
                                                                     '—@Genius',
                                            'annotatable': {'_type': 'cover_art',
                                                            'api_path': '/albums/102298',
                                                            'context': 'Chris '
                                                                       'Cornell',
                                                            'id': 21402,
                                                            'image_url': 'https://images.genius.com/dc9148a9c2eb963ae0b5564ef2042412.300x300x1.jpg',
                                                            'link_title': 'Euphoria '
                                                                          'Mourning',
                                                            'title': 'Euphoria '
                                                                     'Mourning',
                                                            'type': 'CoverArt',
                                                            'url': 'https://genius.com/album_cover_arts/21402'},
                                            'annotations': [{'_type': 'annotation',
                                                             'api_path': '/annotations/12001602',
                                                             'being_created': False,
                                                             'body': {'plain': ''},
                                                             'comment_count': 0,
                                                             'community': True,
                                                             'created_at': 1496876077,
                                                             'custom_preview': None,
                                                             'deleted': False,
                                                             'embed_content': '<blockquote '
                                                                              "class='rg_standalone_container' "
                                                                              "data-src='//genius.com/annotations/12001602/standalone_embed'><a "
                                                                              "href='https://genius.com/12001602/Euphoria-mourning/Https-imagesgeniuscom-dc9148a9c2eb963ae0b5564ef20424121000x1000x1jpg'>https://images.genius.com/dc9148a9c2eb963ae0b5564ef2042412.1000x1000x1.jpg</a><br><a "
                                                                              "href='https://genius.com/album_cover_arts/21402'>&#8213; "
                                                                              'Euphoria '
                                                                              'Mourning</a></blockquote><script '
                                                                              'async '
                                                                              'crossorigin '
                                                                              "src='//genius.com/annotations/load_standalone_embeds.js'></script>",
                                                             'has_voters': False,
                                                             'id': 12001602,
                                                             'needs_exegesis': True,
                                                             'pinned': False,
                                                             'proposed_edit_count': 0,
                                                             'pyongs_count': None,
                                                             'referent_id': 12001602,
                                                             'share_url': 'https://genius.com/12001602',
                                                             'source': None,
                                                             'state': 'needs_exegesis',
                                                             'twitter_share_message': '“?” '
                                                                                      '—@Genius',
                                                             'url': 'https://genius.com/12001602/Euphoria-mourning/Https-imagesgeniuscom-dc9148a9c2eb963ae0b5564ef20424121000x1000x1jpg',
                                                             'verified': False,
                                                             'votes_total': 0,
                                                             'current_user_metadata': {'permissions': [],
                                                                                       'excluded_permissions': ['vote',
                                                                                                                'edit',
                                                                                                                'cosign',
                                                                                                                'uncosign',
                                                                                                                'destroy',
                                                                                                                'accept',
                                                                                                                'reject',
                                                                                                                'see_unreviewed',
                                                                                                                'clear_votes',
                                                                                                                'propose_edit_to',
                                                                                                                'pin_to_profile',
                                                                                                                'unpin_from_profile',
                                                                                                                'update_source',
                                                                                                                'edit_custom_preview',
                                                                                                                'report_as_abusive',
                                                                                                                'create_comment'],
                                                                                       'interactions': {'cosign': False,
                                                                                                        'pyong': False,
                                                                                                        'vote': None},
                                                                                       'iq_by_action': {}},
                                                             'accepted_by': None,
                                                             'authors': [{'_type': 'user_attribution',
                                                                          'attribution': 1.0,
                                                                          'pinned_role': None,
                                                                          'user': {'_type': 'user',
                                                                                   'about_me_summary': 'Hi! '
                                                                                                       'I’m '
                                                                                                       'the '
                                                                                                       'Genius '
                                                                                                       'Bot, '
                                                                                                       'a '
                                                                                                       'robotic '
                                                                                                       'user '
                                                                                                       'who '
                                                                                                       'performs '
                                                                                                       'automated '
                                                                                                       'tasks '
                                                                                                       'on '
                                                                                                       'the '
                                                                                                       'site. '
                                                                                                       'My '
                                                                                                       'behavior '
                                                                                                       'was '
                                                                                                       'programmed '
                                                                                                       'by '
                                                                                                       'the '
                                                                                                       'tech '
                                                                                                       'team, '
                                                                                                       'and '
                                                                                                       'my '
                                                                                                       'job '
                                                                                                       'is '
                                                                                                       'to '
                                                                                                       'help '
                                                                                                       'keep '
                                                                                                       'the '
                                                                                                       'site’s '
                                                                                                       'data '
                                                                                                       'crisp '
                                                                                                       'and '
                                                                                                       'clean.\n'
                                                                                                       '\n'
                                                                                                       'If '
                                                                                                       'I’ve '
                                                                                                       'rejected '
                                                                                                       'or '
                                                                                                       'deleted '
                                                                                                       'your '
                                                                                                       'annotation, '

In [2]:
%run data_cleaning-no-punctuation.ipynb

{'_type': 'album',
 'api_path': '/albums/102298',
 'cover_art_thumbnail_url': 'https://images.genius.com/dc9148a9c2eb963ae0b5564ef2042412.300x300x1.jpg',
 'cover_art_url': 'https://images.genius.com/dc9148a9c2eb963ae0b5564ef2042412.1000x1000x1.jpg',
 'full_title': 'Euphoria Mourning by Chris Cornell',
 'id': 102298,
 'name': 'Euphoria Mourning',
 'name_with_artist': 'Euphoria Mourning (artist: Chris Cornell)',
 'primary_artist_names': 'Chris Cornell',
 'pusher_channel': 'album-102298',
 'release_date_components': {'year': 1999, 'month': 9, 'day': 21},
 'release_date_for_display': 'September 21, 1999',
 'updated_at': 1739842718,
 'url': 'https://genius.com/albums/Chris-cornell/Euphoria-mourning',
 'current_user_metadata': {'permissions': ['create_comment'],
                           'excluded_permissions': ['set_album_color_gradient',
                                                    'edit',
                                                    'destroy',
                                                    'pyong',
                                                    'lock',
                                                    'super_lock',
                                                    'unlock',
                                                    'sort_songs',
                                                    'hide',
                                                    'unhide',
                                                    'see_short_id',
                                                    'create_additional_role',
                                                    'create_question'],
                           'interactions': {'pyong': False, 'following': False},
                           'iq_by_action': {}},
 'artist': 'Chris Cornell',
 'primary_artists': [{'_type': 'artist',
                      'api_path': '/artists/18435',
                      'header_image_url': 'https://images.genius.com/b6a79ad3d1aa69a9dfb83168a82022f7.473x281x1.png',
                      'id': 18435,
                      'image_url': 'https://images.genius.com/13f0e2fe12d710928b62ec5a98778cc3.1000x1000x1.jpg',
                      'index_character': 'c',
                      'is_meme_verified': False,
                      'is_verified': False,
                      'links_config': None,
                      'name': 'Chris Cornell',
                      'slug': 'Chris-cornell',
                      'url': 'https://genius.com/artists/Chris-cornell'}],
 'album_type': 'album',
 'comment_count': 0,
 'custom_header_image_url': 'https://images.genius.com/588bfe15d081baa0ae31ed59960244c0.461x251x1.png',
 'description_preview': '',
 'header_image_url': 'https://images.genius.com/588bfe15d081baa0ae31ed59960244c0.461x251x1.png',
 'hidden': False,
 'language': None,
 'lock_state': 'editable',
 'pyongs_count': 0,
 'release_date': '1999-09-21',
 'tracking_paths': {'aggregate': '/albums/Chris-cornell/Euphoria-mourning',
                    'concurrent': '/albums/Chris-cornell/Euphoria-mourning'},
 'viewable_by_roles': [],
 'album_art_primary_color': '#b7bc57',
 'album_art_secondary_color': '#a0cbd6',
 'album_art_text_color': '#000',
 'song_pageviews': 138643,
 'album_relationships': [{'_type': 'album_relationship',
                          'relationship_type': 'deluxe_edition_of',
                          'albums': []},
                         {'_type': 'album_relationship',
                          'relationship_type': 'has_deluxe_edition',
                          'albums': []},
                         {'_type': 'album_relationship',
                          'relationship_type': 'alternate_version_of',
                          'albums': []},
                         {'_type': 'album_relationship',
                          'relationship_type': 'has_alternate_version',
                          'albums': []},
                         {'_type': 'album_relationship',
                          'relationship_type': 'reissue_of',
                          'albums': []},
                         {'_type': 'album_relationship',
                          'relationship_type': 'has_reissue',
                          'albums': []},
                         {'_type': 'album_relationship',
                          'relationship_type': 'remix_version_of',
                          'albums': []},
                         {'_type': 'album_relationship',
                          'relationship_type': 'has_remix_version',
                          'albums': []}],
 'cover_arts': [{'_type': 'cover_art',
                 'annotated': False,
                 'api_path': '/albums/102298',
                 'id': 21402,
                 'image_url': 'https://images.genius.com/dc9148a9c2eb963ae0b5564ef2042412.1000x1000x1.jpg',
                 'thumbnail_image_url': 'https://images.genius.com/dc9148a9c2eb963ae0b5564ef2042412.300x300x1.jpg',
                 'url': 'https://genius.com/album_cover_arts/21402',
                 'current_user_metadata': {'permissions': [],
                                           'excluded_permissions': ['destroy']},
                 'description_annotation': {'_type': 'referent',
                                            'annotator_id': 2937273,
                                            'annotator_login': 'geniusbot',
                                            'api_path': '/referents/12001602',
                                            'classification': 'needs_exegesis',
                                            'fragment': 'https://images.genius.com/dc9148a9c2eb963ae0b5564ef2042412.1000x1000x1.jpg',
                                            'id': 12001602,
                                            'ios_app_url': 'genius://referents/12001602',
                                            'is_description': True,
                                            'is_image': True,
                                            'path': '/12001602/Euphoria-mourning/Https-imagesgeniuscom-dc9148a9c2eb963ae0b5564ef20424121000x1000x1jpg',
                                            'range': {'content': 'https://images.genius.com/dc9148a9c2eb963ae0b5564ef2042412.1000x1000x1.jpg'},
                                            'song_id': None,
                                            'url': 'https://genius.com/12001602/Euphoria-mourning/Https-imagesgeniuscom-dc9148a9c2eb963ae0b5564ef20424121000x1000x1jpg',
                                            'verified_annotator_ids': [],
                                            'current_user_metadata': {'permissions': [],
                                                                      'excluded_permissions': ['add_pinned_annotation_to',
                                                                                               'add_community_annotation_to'],
                                                                      'relationships': {}},
                                            'tracking_paths': {'aggregate': '/12001602/Euphoria-mourning/Https-imagesgeniuscom-dc9148a9c2eb963ae0b5564ef20424121000x1000x1jpg',
                                                               'concurrent': '/albums/Chris-cornell/Euphoria-mourning'},
                                            'twitter_share_message': '“?” '
                                                                     '—@Genius',
                                            'annotatable': {'_type': 'cover_art',
                                                            'api_path': '/albums/102298',
                                                            'context': 'Chris '
                                                                       'Cornell',
                                                            'id': 21402,
                                                            'image_url': 'https://images.genius.com/dc9148a9c2eb963ae0b5564ef2042412.300x300x1.jpg',
                                                            'link_title': 'Euphoria '
                                                                          'Mourning',
                                                            'title': 'Euphoria '
                                                                     'Mourning',
                                                            'type': 'CoverArt',
                                                            'url': 'https://genius.com/album_cover_arts/21402'},
                                            'annotations': [{'_type': 'annotation',
                                                             'api_path': '/annotations/12001602',
                                                             'being_created': False,
                                                             'body': {'plain': ''},
                                                             'comment_count': 0,
                                                             'community': True,
                                                             'created_at': 1496876077,
                                                             'custom_preview': None,
                                                             'deleted': False,
                                                             'embed_content': '<blockquote '
                                                                              "class='rg_standalone_container' "
                                                                              "data-src='//genius.com/annotations/12001602/standalone_embed'><a "
                                                                              "href='https://genius.com/12001602/Euphoria-mourning/Https-imagesgeniuscom-dc9148a9c2eb963ae0b5564ef20424121000x1000x1jpg'>https://images.genius.com/dc9148a9c2eb963ae0b5564ef2042412.1000x1000x1.jpg</a><br><a "
                                                                              "href='https://genius.com/album_cover_arts/21402'>&#8213; "
                                                                              'Euphoria '
                                                                              'Mourning</a></blockquote><script '
                                                                              'async '
                                                                              'crossorigin '
                                                                              "src='//genius.com/annotations/load_standalone_embeds.js'></script>",
                                                             'has_voters': False,
                                                             'id': 12001602,
                                                             'needs_exegesis': True,
                                                             'pinned': False,
                                                             'proposed_edit_count': 0,
                                                             'pyongs_count': None,
                                                             'referent_id': 12001602,
                                                             'share_url': 'https://genius.com/12001602',
                                                             'source': None,
                                                             'state': 'needs_exegesis',
                                                             'twitter_share_message': '“?” '
                                                                                      '—@Genius',
                                                             'url': 'https://genius.com/12001602/Euphoria-mourning/Https-imagesgeniuscom-dc9148a9c2eb963ae0b5564ef20424121000x1000x1jpg',
                                                             'verified': False,
                                                             'votes_total': 0,
                                                             'current_user_metadata': {'permissions': [],
                                                                                       'excluded_permissions': ['vote',
                                                                                                                'edit',
                                                                                                                'cosign',
                                                                                                                'uncosign',
                                                                                                                'destroy',
                                                                                                                'accept',
                                                                                                                'reject',
                                                                                                                'see_unreviewed',
                                                                                                                'clear_votes',
                                                                                                                'propose_edit_to',
                                                                                                                'pin_to_profile',
                                                                                                                'unpin_from_profile',
                                                                                                                'update_source',
                                                                                                                'edit_custom_preview',
                                                                                                                'report_as_abusive',
                                                                                                                'create_comment'],
                                                                                       'interactions': {'cosign': False,
                                                                                                        'pyong': False,
                                                                                                        'vote': None},
                                                                                       'iq_by_action': {}},
                                                             'accepted_by': None,
                                                             'authors': [{'_type': 'user_attribution',
                                                                          'attribution': 1.0,
                                                                          'pinned_role': None,
                                                                          'user': {'_type': 'user',
                                                                                   'about_me_summary': 'Hi! '
                                                                                                       'I’m '
                                                                                                       'the '
                                                                                                       'Genius '
                                                                                                       'Bot, '
                                                                                                       'a '
                                                                                                       'robotic '
                                                                                                       'user '
                                                                                                       'who '
                                                                                                       'performs '
                                                                                                       'automated '
                                                                                                       'tasks '
                                                                                                       'on '
                                                                                                       'the '
                                                                                                       'site. '
                                                                                                       'My '
                                                                                                       'behavior '
                                                                                                       'was '
                                                                                                       'programmed '
                                                                                                       'by '
                                                                                                       'the '
                                                                                                       'tech '
                                                                                                       'team, '
                                                                                                       'and '
                                                                                                       'my '
                                                                                                       'job '
                                                                                                       'is '
                                                                                                       'to '
                                                                                                       'help '
                                                                                                       'keep '
                                                                                                       'the '
                                                                                                       'site’s '
                                                                                                       'data '
                                                                                                       'crisp '
                                                                                                       'and '
                                                                                                       'clean.\n'
                                                                                                       '\n'
                                                                                                       'If '
                                                                                                       'I’ve '
                                                                                                       'rejected '
                                                                                                       'or '
                                                                                                       'deleted '
                                                                                                       'your '
                                                                                                       'annotation, '

In [3]:
#https://pudding.cool/projects/vocabulary/index.html
#https://www.nltk.org/book/ch01.html#counting-vocabulary

In [4]:
#import nltk

In [5]:
#Test for one song 

text = chris_cornell_df_without_labels['processed_track_lyrics'].iloc[0].split()
def lexical_diversity(text):
    if len(text) == 0:
        return 0
    return len(set(text)) / len(text)
#https://www.nltk.org/book/ch01.html#counting-vocabulary 
#need to split because processed_track_lyrics joined the tokens created with spacy

lexical_diversity(text)

#0.26973684210526316
#about 27 of every 100 words is unique for the first song in 'processed_track_lyrics' column

0.26973684210526316

In [6]:
#Loop for lexical diversity value for each song in 'processed_track_lyrics' column 

song_word_diversity_df = chris_cornell_df_without_labels[["album_name", "track_title", "processed_track_lyrics", "release_year", "track_lyrics"]].copy()

In [7]:
#Create new lists to add as new columns to new dataframe 

word_diversity_score = []
word_count_processed_lyrics = []
unique_text_count_processed_lyrics = []

text = song_word_diversity_df['processed_track_lyrics']

for text in song_word_diversity_df["processed_track_lyrics"]:
    tokens = text.split()
    def lexical_diversity(text):
        if len(text) == 0:
            return 0
        return len(set(text)) / len(text)
    word_diversity_score.append(lexical_diversity(tokens) * 100)
    word_count_processed_lyrics.append(len(tokens))
    unique_text_count_processed_lyrics.append(len(set(tokens)))

    
song_word_diversity_df["word_diversity_score"] = word_diversity_score
song_word_diversity_df["unique_text_count_processed_lyrics"] = unique_text_count_processed_lyrics
song_word_diversity_df["word_count_processed_lyrics"] = word_count_processed_lyrics

song_word_diversity_df = song_word_diversity_df[
    ["album_name", "release_year", "track_title", "word_diversity_score", "unique_text_count_processed_lyrics", "word_count_processed_lyrics", "processed_track_lyrics", "track_lyrics"]
]

In [8]:
song_word_diversity_df.reset_index(drop=True, inplace=True)

In [9]:
pd.options.display.max_rows = None
song_word_diversity_df.sort_values("word_diversity_score", ascending=False).head(10)

,album_name,release_year,track_title,word_diversity_score,unique_text_count_processed_lyrics,word_count_processed_lyrics,processed_track_lyrics,track_lyrics
35,Ultramega OK,1988,Circle of Power,74.074074,40,54,day finally come smell revenge sweet strong rekindle flames rage assholes they burn knees we live fear trembling words apology bullet list' x' accomplished deed ol' big badass circle power comin' ya not necessarily dumb beautiful beautiful it's circle power it's it's circle spinnin' circle power it's different names circle power it's circle power,"[Verse 1] The day will finally come and The smell of revenge, so sweet and strong Rekindle the flames of rage All those assholes, they burn on their knees [Verse 2] Well, here we live To see their fear and their trembling words of apology A bullet for every name on the list An 'X' for every accomplished deed Ol' big badass circle of power is comin' to get ya! [Guitar Solo and vocal ad-libs] [Interlude] Not necessarily dumb, but just, uh…beautiful Beautiful [Outro] Well, it's the circle of power And it's all, it's all the same Ah, the circle, spinnin' the circle of power And it's under different names Oh, the circle of power, it's all the same The circle of power"
29,Ultramega OK,1988,Flower,73.770492,45,61,her vain parade her veins seventeen eyes purple green treated like queen she was borrowed selfesteem she would do her dance painful masquerade spinning you her web her vain parade her uniform studded brass steel kissing napkin lipstick stains smearing sincerity her vain parade her veins break time crept her she's early gray her reflection looks concerned flowers hit her grave,"[Intro] Along her vain parade Along her veins Huah! [Verse 1] All of seventeen, eyes a purple green Treated like a queen, she was on borrowed self-esteem [Verse 2] She would do her dance, a painful masquerade Spinning you into her web along her vain parade [Verse 3] In her uniform of studded brass and steel Kissing napkin, lipstick stains, and smearing sincerity [Chorus] Along her vain parade Along her veins [Instrumental Break] Heyyyy-ya-la-la-hey-hey [Verse 4] Time crept up on her, she's in early gray Her reflection looks concerned as flowers hit her grave"
8,Euphoria Mourning,1999,Sweet Euphoria,71.111111,64,90,sweet euphoria heart you you lost grace hands that harmed you daze thousand yawns lost love it i'm truly gone morning i sleep fire open palm death jesus plastic armies wouldn't bring me sweet ether eyes i'm blind them aching hour time wilts like flowers sleeping landmine pillows tired angels save love lasting sweet euphoria heart you stole touched broken things you love stars light candles warms face i can't remember gone dandelions falling like falling like daydream mangos diving swallows save love save love save love lasting sweet euphoria,"[Verse] Sweet euphoria Mine is the heart you own You lost the grace of the hands that harmed you In the daze of a thousand yawns Lost my love, as it is I'm truly gone In your morning I will sleep Fire on an open palm Death for Jesus and plastic armies Wouldn't bring me back again Sweet as ether eyes I'm blind to them [Chorus] And in your aching hour Time wilts like flowers Sleeping on land-mine pillows Tired angels Save my love for the lasting one [Verse 2] Sweet euphoria Mine is heart you stole Touched and broken are the things you love Using stars to light your candles Warms my face but I can't remember yours [Chorus] Gone are your dandelions Falling like mine Falling like daydream mangos Diving swallows Save my love, save my love Save my love for the lasting one Sweet Euphoria"
33,Ultramega OK,1988,667,68.181818,15,22,kill them steal gold feed boy's killer feed young prepare it save you feed boy hates kill feed young feed young cool,"[Interlude] Kill them all Steal their gold Feed my boy's killer Feed the young, prepare it, save you Feed the boy, hates to kill Feed the young Feed the young [Outro] (Cool)"
17,Higher Truth,2015,Through the Window,65.625000,105,160,clouds gathered turned rain candle sill burned weather face timed match mood outside reading poems that you saved they gloomy hours sense do they lose power yellowing age i saw you suffering foggy window rain you thought no was watching going memories like prisons escape face no suffering you sold best yourself chain gray white light syllable time you them pay higher price i saw you suffering cracked dirty window pane i was ashamed that i was watching going imagination looking life you create somebody face no suffering i wish that i find seed plant tree that grows high that i climb harvest ripe stars you i drink spit ashes our mouthes gray clouds send them packing bags old regrets sorrows cuz they do do thing drag us far past like braided rope moment tightly coiled inside i saw you suffering yellow window train everybody watching tired imagining that you love somebody far away time place life face no suffering,"Clouds have gathered turned to rain Candle on your sill burned out Weather on your face Timed to match the mood outside Reading the poems that you saved They make the gloomy hours make sense Or do they lose their power With the yellowing of age I saw you suffering Through a foggy window in the rain When you thought no one was watching, yeah Going through your memories like so many prisons to escape Become someone else With another face And another name No more suffering You sold the best of yourself out On a chain of gray and white light One syllable at a time You should have made them pay a higher price I saw you suffering Through the cracked and dirty window pane I was ashamed that I was watching Going through your imagination Looking for a life you could create And become somebody else With another face And another name No more suffering I wish that I could find a seed and Plant a tree that grows so high So that I could climb And harvest the ripe stars For you and I to drink and Spit the ashes from our mouthes And put the gray back in the clouds Send them packing without bags Of old regrets and sorrows Cuz they don’t do a thing But drag us down So far down The past is like a braided rope Each moment tightly coiled inside I saw you suffering Through the yellow window of the train With everybody watching, yeah Too tired for imagining That you could ever love somebody else Somewhere far away From another time And another place With another life And another face And another name And another name No more suffering"
23,Higher Truth,2015,Circling,65.322581,81,124,night falls drunken angels sleep road i'm nodding stairwell trying stay cold circling drain ca find way home road long never ends dark heart that wanders light breaks window takes minute know i dying blackbird gives his soul wind roof house that i bed circling drain me way home road long never ends dark heart that wanders i crawl thousand miles eyes look me i steal you flowers bloodshot light lonely hours moonless night like stray dog rain i run night i picture you underneath porch light calling night waiting me i thought i heard voice water i walked fountain uptown i'm orphan door church watching water calm circling drain hope that i it home i never felt far away dark heart that wanders,[Verse 1] Night falls while drunken angels Sleep by the side of the road Now I'm nodding in the stairwell Just trying to stay out of the cold [Chorus] Circling around the drain Can’t find my way back home The road is long and never ends Dark is the heart that wanders [Verse 2] Light breaks in through the window Takes a minute to know where I am A dying blackbird gives his soul to the wind On the roof of the house that I can see from my bed [Chorus] Circling around the drain Show me the way back home The road is long and never ends Dark is the heart that wanders [Bridge] I'd crawl a hundred thousand miles Just to see your two eyes look me over I’d steal you flowers in the bloodshot light Of lonely hours on a moonless night Just like a stray dog in the rain I can run all night and get nowhere I picture you out underneath the porch light Calling my name all night and waiting for me [Verse 3] I thought I heard your voice in the water As I walked by a fountain uptown Now I'm an orphan at the door of a church Just watching the water calm down [Chorus] Circling around the drain Hope that I make it home I’ve never felt so far away Dark is the heart that wanders
49,King Animal,2012,Attrition,64.772727,57,88,lay bombast gloom parade ghouls marches headed nero's tomb raising flags burning rights warm yourself godmade fire pinocchio spinning eyes laugh aloud bomblit skies victim's smile never lies you lived life like joke no time you going do it you punchline right cliff stormy waves can't decide climb drown folly disgrace thumbs overwritten ladder poison find new way you gonna do it you gonna do it you gonna do it you gonna do it you lived life like joke no time you lived life like joke no time,"[Verse] Lay here under bombast and gloom Parade of ghouls marches by Headed down to Nero's tomb Raising flags and burning rights [Verse] Warm yourself by a god-made fire Pinocchio with spinning eyes Laugh aloud under bomb-lit skies A victim's smile never lies [Bridge] You have always lived your life like a joke with no time What you going to do about it until you get the punchline right? [Verse] On the cliff above stormy waves Can't decide to climb or drown Up is folly and down disgrace Under thumbs over-written The ladder is poison, have to find a new way around [Outro] What you gonna do about it? What you gonna do about it? What you gonna do about it? What you gonna do about it? You've always lived your life like a joke with no time You've always lived your life like a joke with no time ""Think it's on D"" ""I think so"" ""I just hit the wrong chord"""
32,Ultramega OK,1988,Beyond the Wheel,63.380282,45,71,far road house home churning storm hailing burning bones tiny baby cries little tiny pawn profit game tiny baby grows mother man he doin' he proper home home overturning stones stones father mighty man loves his little boys boys shows them kill save his precious stones stones break far wheel spin life driving flesh blood deep ground ground break far wheel it steers life driving flesh blood blood deep ground ground,"[Verse 1] Far beyond the road Between your house and home There is a churning storm Of hailing, burning bones Tiny baby cries Little, tiny pawn In the profit game Tiny baby grows [Verse 2] Mother, who’s your man? Is he doin' what he can To make a proper home, home By overturning other stones, stones? Father, mighty man Loves his little boys, boys Shows them how to kill To save his precious stones, stones [Instrumental Break] [Hook] Far beyond the wheel Spin your life around By driving flesh and blood Deep into the ground, ground [Instrumental Break] [Hook] Far beyond the wheel It steers your life around By driving flesh and blood, blood Deep into the ground, the ground [Guitar Solo]"
34,Ultramega OK,1988,Mood for Trouble,60.000000,33,55,mood was swing mood was swing i wanted free rituals stale i did not want hear perfect thing dying squeeze ugly truth hear admit you believed perfect pool lies you it that would right i did not wanna fight i did not wanna kill i wanted real i wanted believe that i was not alive,"[Verse 1] My mood was in full swing My mood was in full swing I wanted to be free From rituals so stale I did not want to hear The perfect thing to say Dying to squeeze out The ugly truth for everyone to hear [Bridge] Admit, you believed Your perfect pool of lies And now, if you could say it That everything would be all right Everything done [Verse 2] I did not wanna fight I did not wanna kill I wanted to be real I wanted to believe That I was not the only one alive [Instrumental Outro]"
3,Euphoria Mourning,1999,Follow My Way,60.000000,78,130,little don't fool i'm wreck i look mighty euphoria i'm bruised confusion i'm lightning complacence i small oblivion i'm charged follow way i'm not leading open frayed you that i'm unsure way i'm pure i lost you're needing you're finding that i'm not you're looking boy bathed infrared sunlight i'm polish reward i'm confident i'm hopeless like everybody right they fall apart follow way i falling heart i'm pain fever sweet relief way i'm not worthy trust follow me swan dive eyes closed tight lowly slowly i know i love you you're gone warm hands inside veins i contagious oblivion i charge follow way i useless cause i derail calm patience remorse way open nerves you know that i don't know we you know that i don't know follow way,"[Verse 1] Little one, don't be a fool I'm a wreck when I look mighty In euphoria, I'm bruised In confusion, next I'm lightning In complacence, I am small Through oblivion I'm charged [Chorus] Follow my way when I'm not leading anyone Open and frayed when you can see that I'm unsure Out on my way, I'm only pure when I get lost And you're only needing when you're finding that I'm not [Verse 2] You're just looking for a boy Bathed in infrared and sunlight I'm all polish and reward When I'm confident, I'm hopeless Just like everybody else Right before they fall apart [Chorus] So follow my way when I am falling from your heart When I'm the pain, fever, and sweet relief in one Out on my way, though I'm not worthy of your trust Follow me down into a swan dive, all eyes closed tight [Bridge] Lowly, slowly, now I know I love where you go when you're gone Warm your hands inside my veins I might be contagious Through oblivion, I charge [Chorus] So follow my way when I am useless to your cause When I derail, calm in the patience of remorse Out on my way, out on my empty open nerves When all you know is that I don't know where we are When all you know is that I don't know Follow my way"

In [10]:
top_10_diverse_df = song_word_diversity_df.sort_values("word_diversity_score", ascending=False)[['track_title', "release_year", 'album_name', 'word_diversity_score', 'unique_text_count_processed_lyrics', 'word_count_processed_lyrics']].head(10).reset_index(drop=True).copy()

Question 5: What are the top 10 songs by word diversity? 

0       Circle of Power
1                Flower
2        Sweet Euphoria
3                   667
4    Through the Window
5              Circling
6             Attrition
7      Beyond the Wheel
8      Mood for Trouble
9         Follow My Way

In [11]:
top_10_diverse_df['word_diversity_score']=top_10_diverse_df['word_diversity_score'].round(0)
top_10_diverse_df

,track_title,release_year,album_name,word_diversity_score,unique_text_count_processed_lyrics,word_count_processed_lyrics
0,Circle of Power,1988,Ultramega OK,74.0,40,54
1,Flower,1988,Ultramega OK,74.0,45,61
2,Sweet Euphoria,1999,Euphoria Mourning,71.0,64,90
3,667,1988,Ultramega OK,68.0,15,22
4,Through the Window,2015,Higher Truth,66.0,105,160
5,Circling,2015,Higher Truth,65.0,81,124
6,Attrition,2012,King Animal,65.0,57,88
7,Beyond the Wheel,1988,Ultramega OK,63.0,45,71
8,Mood for Trouble,1988,Ultramega OK,60.0,33,55
9,Follow My Way,1999,Euphoria Mourning,60.0,78,130

In [12]:
scatter_song_word_diversity_df=song_word_diversity_df.copy()

In [13]:
scatter_song_word_diversity_df = scatter_song_word_diversity_df.drop(columns = ['track_lyrics', 'processed_track_lyrics', "unique_text_count_processed_lyrics", "word_count_processed_lyrics"])

In [14]:
scatter_song_word_diversity_df=scatter_song_word_diversity_df[['track_title', "album_name", 'release_year', 'word_diversity_score']]

In [15]:
scatter_song_word_diversity_df

,track_title,album_name,release_year,word_diversity_score
0,Can’t Change Me,Euphoria Mourning,1999,26.973684
1,Flutter Girl,Euphoria Mourning,1999,39.230769
2,Preaching the End of the World,Euphoria Mourning,1999,39.306358
3,Follow My Way,Euphoria Mourning,1999,60.000000
4,When I’m Down,Euphoria Mourning,1999,45.192308
5,Mission,Euphoria Mourning,1999,56.626506
6,Wave Goodbye,Euphoria Mourning,1999,53.921569
7,Moonchild,Euphoria Mourning,1999,48.672566
8,Sweet Euphoria,Euphoria Mourning,1999,71.111111
9,Disappearing One,Euphoria Mourning,1999,39.583333
10,Pillow of Your Bones,Euphoria Mourning,1999,46.969697
11,Steel Rain,Euphoria Mourning,1999,41.666667
12,Sunshower,Euphoria Mourning,1999,42.857143
13,Nearly Forgot My Broken Heart,Higher Truth,2015,43.859649
14,Dead Wishes,Higher Truth,2015,54.761905
15,Worried Moon,Higher Truth,2015,48.863636
16,Before We Disappear,Higher Truth,2015,40.000000
17,Through the Window,Higher Truth,2015,65.625000
18,Josephine,Higher Truth,2015,55.468750
19,Murderer of Blue Skies,Higher Truth,2015,33.727811
20,Higher Truth,Higher Truth,2015,30.409357
21,Let Your Eyes Wander,Higher Truth,2015,52.702703
22,Only These Words,Higher Truth,2015,55.813953
23,Circling,Higher Truth,2015,65.322581
24,Our Time In the Universe,Higher Truth,2015,52.336449
25,Bend In the Road,Higher Truth,2015,55.660377
26,Wrong Side,Higher Truth,2015,55.319149
27,Misery Chain (Bonus Track),Higher Truth,2015,52.727273
28,Our Time In the Universe (Remix),Higher Truth,2015,51.886792
29,Flower,Ultramega OK,1988,73.770492
30,All Your Lies,Ultramega OK,1988,25.954198
31,665,Ultramega OK,1988,51.612903
32,Beyond the Wheel,Ultramega OK,1988,63.380282
33,667,Ultramega OK,1988,68.181818
34,Mood for Trouble,Ultramega OK,1988,60.000000
35,Circle of Power,Ultramega OK,1988,74.074074
36,He Didn’t,Ultramega OK,1988,38.636364
37,Smokestack Lightning,Ultramega OK,1988,46.153846
38,Nazi Driver,Ultramega OK,1988,28.888889
39,Head Injury,Ultramega OK,1988,19.718310
40,Incessant Mace,Ultramega OK,1988,50.000000
41,One Minute of Silence,Ultramega OK,1988,0.000000
42,Been Away Too Long,King Animal,2012,43.548387
43,Non-State Actor,King Animal,2012,46.762590
44,By Crooked Steps,King Animal,2012,34.558824
45,A Thousand Days Before,King Animal,2012,51.612903
46,Blood on the Valley Floor,King Animal,2012,59.183673
47,Bones of Birds,King Animal,2012,40.449438
48,Taree,King Animal,2012,39.361702
49,Attrition,King Animal,2012,64.772727
50,Black Saturday,King Animal,2012,35.245902
51,Halfway There,King Animal,2012,53.398058
52,Worse Dreams,King Animal,2012,50.000000
53,Eyelid’s Mouth,King Animal,2012,28.282828
54,Rowing,King Animal,2012,27.966102
55,Cochise,Audioslave,2002,39.215686
56,Show Me How to Live,Audioslave,2002,44.800000
57,Gasoline,Audioslave,2002,49.367089
58,What You Are,Audioslave,2002,28.037383
59,Like a Stone,Audioslave,2002,48.181818
60,Set It Off,Audioslave,2002,35.099338
61,Shadow on the Sun,Audioslave,2002,42.400000
62,I Am the Highway,Audioslave,2002,42.708333
63,Exploder,Audioslave,2002,46.099291
64,Hypnotize,Audioslave,2002,37.837838
65,Bring ’Em Back Alive,Audioslave,2002,54.945055
66,Light My Way,Audioslave,2002,37.068966
67,Getaway Car,Audioslave,2002,37.007874
68,The Last Remaining Light,Audioslave,2002,55.813953
69,Revelations,Revelations,2006,32.926829
70,One and the Same,Revelations,2006,45.054945
71,Sound of a Gun,Revelations,2006,48.412698
72,Until We Fall,Revelations,2006,46.808511
73,Original Fire,Revelations,2006,41.666667
74,Broken City,Revelations,2006,41.764706
75,Somedays,Revelations,2006,40.458015
76,Shape of Things to Come,Revelations,2006,51.937984
77,Jewel of the Summertime,Revelations,2006,38.524590
78,Wide Awake,Revelations,2006,42.857143
79,Nothing Left to Say But Goodbye,Revelations,2006,54.032258
80,Moth,Revelations,2006,32.258065
81,Say Hello 2 Heaven,Temple of the Dog,1991,57.342657
82,Reach Down,Temple of the Dog,1991,49.504950
83,Hunger Strike,Temple of the Dog,1991,25.000000
84,Pushin’ Forward Back,Temple of the Dog,1991,22.162162
85,Call Me a Dog,Temple of the Dog,1991,46.715328
86,Times of Trouble,Temple of the Dog,1991,44.262295
87,Wooden Jesus,Temple of the Dog,1991,34.814815
88,Your Saviour,Temple of the Dog,1991,36.082474
89,Four Walled World,Temple of the Dog,1991,43.220339
90,All Night Thing,Temple of the Dog,1991,37.500000

In [16]:
scatter_song_word_diversity_df.to_csv("scatter_song_word_diversity_df.csv")

In [17]:
song_word_diversity_df.to_csv("song_word_diversity_df.csv")

6. By how much did word diversity change from first album to last album for solo, Soundgarden, and Audioslave?

In [18]:
album_word_diversity_df = song_word_diversity_df.copy()

In [19]:
album_word_diversity_df.loc[album_word_diversity_df['album_name'] == 'Euphoria Mourning', 'unique_text_count_processed_lyrics'].sum()

np.int64(703)

In [20]:
#calculate word diveristy mean for each album 
#use chart to show change 

unique_word_count_euphoriamourning = album_word_diversity_df.loc[album_word_diversity_df['album_name'] == 'Euphoria Mourning', 'unique_text_count_processed_lyrics'].sum()

unique_word_count_highertruth = album_word_diversity_df.loc[album_word_diversity_df['album_name'] == 'Higher Truth', 'unique_text_count_processed_lyrics'].sum()

unique_word_count_ultramegaok = album_word_diversity_df.loc[album_word_diversity_df['album_name'] == 'Ultramega OK', 'unique_text_count_processed_lyrics'].sum()

unique_word_count_kinganimal = album_word_diversity_df.loc[album_word_diversity_df['album_name'] == 'King Animal', 'unique_text_count_processed_lyrics'].sum()

unique_word_count_audioslave = album_word_diversity_df.loc[album_word_diversity_df['album_name'] == 'Audioslave', 'unique_text_count_processed_lyrics'].sum()

unique_word_count_revelations = album_word_diversity_df.loc[album_word_diversity_df['album_name'] == 'Revelations', 'unique_text_count_processed_lyrics'].sum()

In [21]:
total_word_count_euphoriamourning = album_word_diversity_df.loc[album_word_diversity_df['album_name'] == 'Euphoria Mourning', 'word_count_processed_lyrics'].sum()

total_word_count_highertruth = album_word_diversity_df.loc[album_word_diversity_df['album_name'] == 'Higher Truth', 'word_count_processed_lyrics'].sum()

total_word_count_ultramegaok = album_word_diversity_df.loc[album_word_diversity_df['album_name'] == 'Ultramega OK', 'word_count_processed_lyrics'].sum()

total_word_count_kinganimal = album_word_diversity_df.loc[album_word_diversity_df['album_name'] == 'King Animal', 'word_count_processed_lyrics'].sum()

total_word_count_audioslave = album_word_diversity_df.loc[album_word_diversity_df['album_name'] == 'Audioslave', 'word_count_processed_lyrics'].sum()

total_word_count_revelations = album_word_diversity_df.loc[album_word_diversity_df['album_name'] == 'Revelations', 'word_count_processed_lyrics'].sum()

In [22]:
word_diversity_score_euphoriamourning = unique_word_count_euphoriamourning/total_word_count_euphoriamourning*100

word_diversity_score_highertruth = unique_word_count_highertruth/total_word_count_highertruth*100

word_diversity_score_ultramegaok = unique_word_count_ultramegaok/total_word_count_ultramegaok*100

word_diversity_score_kinganimal = unique_word_count_kinganimal/total_word_count_kinganimal*100

word_diversity_score_audioslave = unique_word_count_audioslave/total_word_count_audioslave*100

word_diversity_score_revelations = unique_word_count_revelations/total_word_count_revelations*100

In [23]:
album_word_diversity_df=album_word_diversity_df.drop_duplicates('album_name')

In [24]:
album_word_diversity_df.drop(album_word_diversity_df[album_word_diversity_df["album_name"] == "Temple of the Dog"].index, inplace=True)

In [25]:
album_word_diversity_df.shape

(6, 8)

In [26]:
album_word_diversity_df['average_album_word_diversity']= [word_diversity_score_euphoriamourning,
                                                          word_diversity_score_highertruth,
                                                          word_diversity_score_ultramegaok,
                                                          word_diversity_score_kinganimal,
                                                          word_diversity_score_audioslave,
                                                          word_diversity_score_revelations]

In [27]:
album_word_diversity_df=album_word_diversity_df[['album_name','average_album_word_diversity']].sort_values('average_album_word_diversity',ascending = False)

In [28]:
album_word_diversity_df.reset_index(drop=True, inplace = True)

In [29]:
album_word_diversity_df

          album_name  average_album_word_diversity
0       Higher Truth                     50.154936
1  Euphoria Mourning                     45.827901
2       Ultramega OK                     43.046358
3        Revelations                     42.643229
4         Audioslave                     42.118698
5        King Animal                     41.580042

In [30]:
album_word_diversity_df.loc[0:2, "first_album"] = ['Euphoria Mourning', 'Ultramega OK', 'Audioslave']
album_word_diversity_df.loc[0:2, "last_album"] = ['Higher Truth', 'King Animal', 'Revelations']

album_word_diversity_df["start_value"] = album_word_diversity_df["first_album"].map(
    album_word_diversity_df.set_index("album_name")["average_album_word_diversity"]
)

album_word_diversity_df["end_value"] = album_word_diversity_df["last_album"].map(
    album_word_diversity_df.set_index("album_name")["average_album_word_diversity"]
)

In [31]:
range_chart_df = album_word_diversity_df.drop(columns = ['album_name', 'average_album_word_diversity']).copy()

In [32]:
range_chart_df = range_chart_df.drop(range(3, 6))

In [33]:
range_chart_df.to_csv("range_chart_df.csv")