In [1]:
%run data_gather-Copy1.ipynb

{'_type': 'album',
 'api_path': '/albums/102298',
 'cover_art_thumbnail_url': 'https://images.genius.com/dc9148a9c2eb963ae0b5564ef2042412.300x300x1.jpg',
 'cover_art_url': 'https://images.genius.com/dc9148a9c2eb963ae0b5564ef2042412.1000x1000x1.jpg',
 'full_title': 'Euphoria Mourning by Chris Cornell',
 'id': 102298,
 'name': 'Euphoria Mourning',
 'name_with_artist': 'Euphoria Mourning (artist: Chris Cornell)',
 'primary_artist_names': 'Chris Cornell',
 'pusher_channel': 'album-102298',
 'release_date_components': {'year': 1999, 'month': 9, 'day': 21},
 'release_date_for_display': 'September 21, 1999',
 'updated_at': 1739842718,
 'url': 'https://genius.com/albums/Chris-cornell/Euphoria-mourning',
 'current_user_metadata': {'permissions': ['create_comment'],
                           'excluded_permissions': ['set_album_color_gradient',
                                                    'edit',
                                                    'destroy',
                                                    'pyong',
                                                    'lock',
                                                    'super_lock',
                                                    'unlock',
                                                    'sort_songs',
                                                    'hide',
                                                    'unhide',
                                                    'see_short_id',
                                                    'create_additional_role',
                                                    'create_question'],
                           'interactions': {'pyong': False, 'following': False},
                           'iq_by_action': {}},
 'artist': 'Chris Cornell',
 'primary_artists': [{'_type': 'artist',
                      'api_path': '/artists/18435',
                      'header_image_url': 'https://images.genius.com/b6a79ad3d1aa69a9dfb83168a82022f7.473x281x1.png',
                      'id': 18435,
                      'image_url': 'https://images.genius.com/13f0e2fe12d710928b62ec5a98778cc3.1000x1000x1.jpg',
                      'index_character': 'c',
                      'is_meme_verified': False,
                      'is_verified': False,
                      'links_config': None,
                      'name': 'Chris Cornell',
                      'slug': 'Chris-cornell',
                      'url': 'https://genius.com/artists/Chris-cornell'}],
 'album_type': 'album',
 'comment_count': 0,
 'custom_header_image_url': 'https://images.genius.com/588bfe15d081baa0ae31ed59960244c0.461x251x1.png',
 'description_preview': '',
 'header_image_url': 'https://images.genius.com/588bfe15d081baa0ae31ed59960244c0.461x251x1.png',
 'hidden': False,
 'language': None,
 'lock_state': 'editable',
 'pyongs_count': 0,
 'release_date': '1999-09-21',
 'tracking_paths': {'aggregate': '/albums/Chris-cornell/Euphoria-mourning',
                    'concurrent': '/albums/Chris-cornell/Euphoria-mourning'},
 'viewable_by_roles': [],
 'album_art_primary_color': '#b7bc57',
 'album_art_secondary_color': '#a0cbd6',
 'album_art_text_color': '#000',
 'song_pageviews': 138643,
 'album_relationships': [{'_type': 'album_relationship',
                          'relationship_type': 'deluxe_edition_of',
                          'albums': []},
                         {'_type': 'album_relationship',
                          'relationship_type': 'has_deluxe_edition',
                          'albums': []},
                         {'_type': 'album_relationship',
                          'relationship_type': 'alternate_version_of',
                          'albums': []},
                         {'_type': 'album_relationship',
                          'relationship_type': 'has_alternate_version',
                          'albums': []},
                         {'_type': 'album_relationship',
                          'relationship_type': 'reissue_of',
                          'albums': []},
                         {'_type': 'album_relationship',
                          'relationship_type': 'has_reissue',
                          'albums': []},
                         {'_type': 'album_relationship',
                          'relationship_type': 'remix_version_of',
                          'albums': []},
                         {'_type': 'album_relationship',
                          'relationship_type': 'has_remix_version',
                          'albums': []}],
 'cover_arts': [{'_type': 'cover_art',
                 'annotated': False,
                 'api_path': '/albums/102298',
                 'id': 21402,
                 'image_url': 'https://images.genius.com/dc9148a9c2eb963ae0b5564ef2042412.1000x1000x1.jpg',
                 'thumbnail_image_url': 'https://images.genius.com/dc9148a9c2eb963ae0b5564ef2042412.300x300x1.jpg',
                 'url': 'https://genius.com/album_cover_arts/21402',
                 'current_user_metadata': {'permissions': [],
                                           'excluded_permissions': ['destroy']},
                 'description_annotation': {'_type': 'referent',
                                            'annotator_id': 2937273,
                                            'annotator_login': 'geniusbot',
                                            'api_path': '/referents/12001602',
                                            'classification': 'needs_exegesis',
                                            'fragment': 'https://images.genius.com/dc9148a9c2eb963ae0b5564ef2042412.1000x1000x1.jpg',
                                            'id': 12001602,
                                            'ios_app_url': 'genius://referents/12001602',
                                            'is_description': True,
                                            'is_image': True,
                                            'path': '/12001602/Euphoria-mourning/Https-imagesgeniuscom-dc9148a9c2eb963ae0b5564ef20424121000x1000x1jpg',
                                            'range': {'content': 'https://images.genius.com/dc9148a9c2eb963ae0b5564ef2042412.1000x1000x1.jpg'},
                                            'song_id': None,
                                            'url': 'https://genius.com/12001602/Euphoria-mourning/Https-imagesgeniuscom-dc9148a9c2eb963ae0b5564ef20424121000x1000x1jpg',
                                            'verified_annotator_ids': [],
                                            'current_user_metadata': {'permissions': [],
                                                                      'excluded_permissions': ['add_pinned_annotation_to',
                                                                                               'add_community_annotation_to'],
                                                                      'relationships': {}},
                                            'tracking_paths': {'aggregate': '/12001602/Euphoria-mourning/Https-imagesgeniuscom-dc9148a9c2eb963ae0b5564ef20424121000x1000x1jpg',
                                                               'concurrent': '/albums/Chris-cornell/Euphoria-mourning'},
                                            'twitter_share_message': '“?” '
                                                                     '—@Genius',
                                            'annotatable': {'_type': 'cover_art',
                                                            'api_path': '/albums/102298',
                                                            'context': 'Chris '
                                                                       'Cornell',
                                                            'id': 21402,
                                                            'image_url': 'https://images.genius.com/dc9148a9c2eb963ae0b5564ef2042412.300x300x1.jpg',
                                                            'link_title': 'Euphoria '
                                                                          'Mourning',
                                                            'title': 'Euphoria '
                                                                     'Mourning',
                                                            'type': 'CoverArt',
                                                            'url': 'https://genius.com/album_cover_arts/21402'},
                                            'annotations': [{'_type': 'annotation',
                                                             'api_path': '/annotations/12001602',
                                                             'being_created': False,
                                                             'body': {'plain': ''},
                                                             'comment_count': 0,
                                                             'community': True,
                                                             'created_at': 1496876077,
                                                             'custom_preview': None,
                                                             'deleted': False,
                                                             'embed_content': '<blockquote '
                                                                              "class='rg_standalone_container' "
                                                                              "data-src='//genius.com/annotations/12001602/standalone_embed'><a "
                                                                              "href='https://genius.com/12001602/Euphoria-mourning/Https-imagesgeniuscom-dc9148a9c2eb963ae0b5564ef20424121000x1000x1jpg'>https://images.genius.com/dc9148a9c2eb963ae0b5564ef2042412.1000x1000x1.jpg</a><br><a "
                                                                              "href='https://genius.com/album_cover_arts/21402'>&#8213; "
                                                                              'Euphoria '
                                                                              'Mourning</a></blockquote><script '
                                                                              'async '
                                                                              'crossorigin '
                                                                              "src='//genius.com/annotations/load_standalone_embeds.js'></script>",
                                                             'has_voters': False,
                                                             'id': 12001602,
                                                             'needs_exegesis': True,
                                                             'pinned': False,
                                                             'proposed_edit_count': 0,
                                                             'pyongs_count': None,
                                                             'referent_id': 12001602,
                                                             'share_url': 'https://genius.com/12001602',
                                                             'source': None,
                                                             'state': 'needs_exegesis',
                                                             'twitter_share_message': '“?” '
                                                                                      '—@Genius',
                                                             'url': 'https://genius.com/12001602/Euphoria-mourning/Https-imagesgeniuscom-dc9148a9c2eb963ae0b5564ef20424121000x1000x1jpg',
                                                             'verified': False,
                                                             'votes_total': 0,
                                                             'current_user_metadata': {'permissions': [],
                                                                                       'excluded_permissions': ['vote',
                                                                                                                'edit',
                                                                                                                'cosign',
                                                                                                                'uncosign',
                                                                                                                'destroy',
                                                                                                                'accept',
                                                                                                                'reject',
                                                                                                                'see_unreviewed',
                                                                                                                'clear_votes',
                                                                                                                'propose_edit_to',
                                                                                                                'pin_to_profile',
                                                                                                                'unpin_from_profile',
                                                                                                                'update_source',
                                                                                                                'edit_custom_preview',
                                                                                                                'report_as_abusive',
                                                                                                                'create_comment'],
                                                                                       'interactions': {'cosign': False,
                                                                                                        'pyong': False,
                                                                                                        'vote': None},
                                                                                       'iq_by_action': {}},
                                                             'accepted_by': None,
                                                             'authors': [{'_type': 'user_attribution',
                                                                          'attribution': 1.0,
                                                                          'pinned_role': None,
                                                                          'user': {'_type': 'user',
                                                                                   'about_me_summary': 'Hi! '
                                                                                                       'I’m '
                                                                                                       'the '
                                                                                                       'Genius '
                                                                                                       'Bot, '
                                                                                                       'a '
                                                                                                       'robotic '
                                                                                                       'user '
                                                                                                       'who '
                                                                                                       'performs '
                                                                                                       'automated '
                                                                                                       'tasks '
                                                                                                       'on '
                                                                                                       'the '
                                                                                                       'site. '
                                                                                                       'My '
                                                                                                       'behavior '
                                                                                                       'was '
                                                                                                       'programmed '
                                                                                                       'by '
                                                                                                       'the '
                                                                                                       'tech '
                                                                                                       'team, '
                                                                                                       'and '
                                                                                                       'my '
                                                                                                       'job '
                                                                                                       'is '
                                                                                                       'to '
                                                                                                       'help '
                                                                                                       'keep '
                                                                                                       'the '
                                                                                                       'site’s '
                                                                                                       'data '
                                                                                                       'crisp '
                                                                                                       'and '
                                                                                                       'clean.\n'
                                                                                                       '\n'
                                                                                                       'If '
                                                                                                       'I’ve '
                                                                                                       'rejected '
                                                                                                       'or '
                                                                                                       'deleted '
                                                                                                       'your '
                                                                                                       'annotation, '

In [2]:
# euphoria_mourning_df

# higher_truth_df

# ultramegaok_soundgarden_df

# kinganimal_soundgarden_df

# audioslave_audioslave_df

# revelations_audioslave_df

# temple_dog_df

In [3]:
import pandas as pd
chris_cornell_df_without_labels= pd.concat([euphoria_mourning_df,
           higher_truth_df,
           ultramegaok_soundgarden_df,
           kinganimal_soundgarden_df,
           audioslave_audioslave_df,
           revelations_audioslave_df,
           temple_dog_df])

In [4]:
pd.set_option('display.max_colwidth', None)
chris_cornell_df_without_labels.reset_index(drop=True)

,track_title,track_lyrics,album_name,project_name,release_year,label
0,Can’t Change Me,"[Verse 1]\nShe can do anything at all\nHave anything she pleases\nThe power to change what she thinks is wrong\nBut what could she want with me? Yeah\n\n[Pre-Chorus]\nBut wait just one minute here\nI can see that she's trying to read me\n(Suddenly I know)\n\n[Chorus]\nShe's going to change the world\nShe's going to change the world\nShe's going to change the world\nBut she can't change me\nNo, she can't change me\n\n[Verse 2]\nShe has the daylight at her command\nShe gives the night its dreams, yeah\nShe can uncover your darkest fear\nAnd make you forget you feel it\n\n[Pre-Chorus]\nBut wait just one minute more\nI can see that she's trying to free me\n(Suddenly I know)\n\n[Chorus]\nShe's going to change the world (Going to change the world)\nShe's going to change the world (Going to change the world)\nShe's going to change the world (Going to change)\nBut she can't change me\nNo, she can't change me\n\n[Bridge]\nAnd suddenly I can see everything that's wrong with me, yeah\nBut what can I do? I'm the only thing I really have at all\n\n[Instrumental Break]\n\n[Pre-Chorus]\nBut wait, just, one minute here\nI can see that she's trying to need me\n(Suddenly I know)\n\n[Chorus]\nShe's going to change the world (Going to change the world)\nShe's going to change the world (Going to change the world)\nShe's going to change the world (Going to change)\nBut she can't change me\nNo, she can't change me",Euphoria Mourning,Chris Cornell,1999,A&M Records
1,Flutter Girl,"[Verse 1]\nI'm drinking dust with eyes of rust\nTonight my tears might stain your wings\nSo flutter home because you're better off alone than with me\n\n[Verse 2]\nSo hide your face and tie your lace\nAnd butterflies across your cheek\nForget how soon you become a fool for words when I speak\n\n[Chorus]\nFlutter girl\nYou don't want to know what I live\nYou don't want to take what I give\nBecause I give nothing for free\nYou don't want to know what I live\nYou don't want to take what I give\nBecause I give nothing for free\n\n[Verse 3]\nMy hands are rough, my fingers cold\nAnd your heart's so young and so naive\nTo ever feel for a moment that I might dare to believe\n\n[Chorus]\nFlutter girl\nYou don't want to know what I live\nYou don't want to take what I give\nBecause I give nothing for free\nYou don't want to know what I live\nYou don't want to take what I give\nBecause I give nothing for free\n\n[Bridge]\nI'll tear your wings\nAs I melt in your smile\nAs I run all your colors away\n\n[Chorus]\nFlutter girl\nYou don't want to know what I live\nYou don't want to take what I give\nBecause I give nothing for free\nYou don't want to know what I live\nYou don't want to take what I give\nBecause I give nothing for free\n\n[Outro]\nFlutter girl",Euphoria Mourning,Chris Cornell,1999,A&M Records
2,Preaching the End of the World,"[Verse 1]\nHello, I know there's someone out there\nWho can understand and who's feeling the same way as me\nI'm 24 and I've got everything to live for\nBut I know now that it wasn't meant to be\n\n[Verse]\n'Cause all has been lost and all has been won\nAnd there's nothing left for us to save\nBut now I know that I don't wanna be alone today\nSo if you're finding you've been feeling just the same\n\n[Chorus]\nCall me now, it's alright\nIt's just the end of the world\nYou'll need a friend in the world\n'Cause you can't hide\nSo call and I'll get right back\nIf your intentions are pure\nI'm seeking a friend for the end of the world\n\n[Verse]\nI've got a photograph, I'll send it off today\nYou will see that I am perfectly sane\nNot for a lifetime or ""forever and a day""\n'Cause we know now that just won't be the case\n\n[Chorus]\nSo call me now, it's alright\nIt's just the end of the world\nYou'll need a friend in the world\n'Cause you can't hide\nSo call and I'll get right back\nIf your intentions are pure\nI'm seeking a friend for the end of the world\n\n[Bridge]\nWith no commitment and no confessions\nAnd no little secrets to keep\nNo little children or houses with roses\nJust the end of the world and me\n\n[Verse]\n'Cause all has been gone and all has been done\nAnd there's nothing left for us to save\nBut we could be together as they blow it all away\nAnd we could share in every moment as it breaks\n\n[Chorus]\nSo call me now, it's alright\nIt's just the end of the world\nYou'll need a friend in the world\n'Cause you can't hide\nSo call and I'll get right back\nIf your intentions are pure\nI'm seeking a friend for the end of the world\n\n[Chorus]\nSo call me now, it's alright\nIt's just the end of the world\nYou'll need a friend in the world\n'Cause you can't hide\nSo call and I'll get right back\nIf your intentions are pure\nI'm seeking a friend for the end of the world",Euphoria Mourning,Chris Cornell,1999,A&M Records
3,Follow My Way,"[Verse 1]\nLittle one, don't be a fool\nI'm a wreck when I look mighty\nIn euphoria, I'm bruised\nIn confusion, next I'm lightning\nIn complacence, I am small\nThrough oblivion I'm charged\n\n[Chorus]\nFollow my way when I'm not leading anyone\nOpen and frayed when you can see that I'm unsure\nOut on my way, I'm only pure when I get lost\nAnd you're only needing when you're finding that I'm not\n\n[Verse 2]\nYou're just looking for a boy\nBathed in infrared and sunlight\nI'm all polish and reward\nWhen I'm confident, I'm hopeless\nJust like everybody else\nRight before they fall apart\n\n[Chorus]\nSo follow my way when I am falling from your heart\nWhen I'm the pain, fever, and sweet relief in one\nOut on my way, though I'm not worthy of your trust\nFollow me down into a swan dive, all eyes closed tight\n\n[Bridge]\nLowly, slowly, now I know\nI love where you go when you're gone\nWarm your hands inside my veins\nI might be contagious\nThrough oblivion, I charge\n\n[Chorus]\nSo follow my way when I am useless to your cause\nWhen I derail, calm in the patience of remorse\nOut on my way, out on my empty open nerves\nWhen all you know is that I don't know where we are\nWhen all you know is that I don't know\nFollow my way",Euphoria Mourning,Chris Cornell,1999,A&M Records
4,When I’m Down,"[Verse 1]\nWhat say you now\nThe door is opening on your vigil\nNow I'm in my usual way\nI save my breath, knowing what you're\nYou're wanting me to say\nI only love you when I'm down\n\n[Verse 2]\nYou say that midnight opens its arms to me\nLeaving you alone, then I fly so far away\nUntil the light blurs my vision and I have nowhere to roam\nI only love you when I'm down\nOoo\n\n[Chorus]\nAnd I only love you when I'm down\nAnd I'm only near you when I'm gone\nBut one thing for you to keep in mind, you know\nThat I'm down all the time, all the time\n\n[Verse 3]\nWell, I know you're reaching out and you\nYou need to feel my hand\nYou want to be understood\nYeah, well, I understand\nI know you hold precious little hope for me\nAnd in your happiness, I'm always drowning in my grief\n\n[Chorus]\nAnd I only love you when I'm down, oh-oh\nAnd I'm only near you when I'm gone\nBut one thing for you to keep in mind, you know\nThat I'm down all the time, all the time\n\n[Outro]\nAll the time\nAll the time",Euphoria Mourning,Chris Cornell,1999,A&M Records
...,...,...,...,...,...,...
86,Times of Trouble,"[Verse 1]\nWhen the spoon is hot and the needle's sharp\nAnd you drift away, ooh, I can hear you say\nThat the world in black is upon your back\nAnd your body shakes, so you ditch away\nYeah, and you close the shades\n\n[Chorus 1]\nDon't try to do it, don't try to kill your time, oh\nYeah, you might do it, then you can't change your mind, oh-oh, oh-oh-oh\nYou gotta hold onto your time 'til you break through these times of\nTrouble\n\n[Verse 2]\nWhen you try to talk and the words get hard\nAnd they put you down, don't you stay\nMm-mmm, don't ditch away\n\n[Chorus 2]\nI saw you swingin', yeah, swingin' your mother's sword, oh-oh-oh-oh-oh\nAnd yeah, yeah, yeah, I know you're playin', oh, sometimes the rules get hard, oh-oh, oh-oh-oh\nBut if somebody left you out on a ledge\nIf somebody pushed you over the edge\nYou gotta hold on to your time and break through these times of\nTrouble\n\n[Harmonica Solo]\n\n[Chorus 2]\nI saw you swingin', yeah, swingin' your mother's sword, ooh\nAnd yeah, yeah, yeah, I know you're playin', but oh, sometimes the rules get hard, oh-oh-oh-oh-oh\nBut if somebody left you on out on the ledge\nIf somebody pushed you, you're over the edge\nIf somebody loved you and left you for dead\nYou gotta hold on to your time and break through these times of\nTrouble",Temple of the Dog,Temple of the Dog,1991,A&M Records
87,Wooden Jesus,"[Verse 1]\nWooden Jesus, where are you from?\nKorea or Canada or maybe Taiwan?\nBut I didn't know it was the Holy Land\nBut I believed from the minute the check left my hand, I pray\n\n[Chorus]\nCan I be saved?\nI spent all my money on a future grave\nWooden Jesus, I'll cut you in\nOn twenty percent of my future sin\n\n[Post-Chorus]\nI'll cut you in\n\n[Verse 2]\nYeah, Porcelain Mary, her majesties pure\nLooking for virgin territory\nCoat-hanger halos that don't come cheap\nFrom television shepherds with livin' room sheep, and I pray\n\n[Chorus]\nCan I be saved?\nI spent all my money on a future grave\nWooden Jesus, I'll cut you in\nOn twenty percent of my future sin\n\n[Post-Chorus]\nI'll cut you in\nI'll cut you in\n\n[Guitar Solo]\n\n[Bridge]\nHey, Wooden Jesus, where are you from?\nKorea or Canada or maybe Taiwan?\nBut I didn't know it was the Holy Land!\nBut I believed from the minute the check left my hand!\n\n[Chorus]\nOh, can I be saved?\nI spent all my money on a future grave\nWooden Jesus, I'll cut you in\nOn twenty percent of my future sin\n\n[Outro]\nHey!\nI'll cut you in, I'll cut you in\nI'll cut you in, I'll cut you in\nI'll cut you in, I'll cut you in\nYeah\nOoh-ooh-ooh-ooh, ooh",Temple of the Dog,Temple of the Dog,1991,A&M Records
88,Your Saviour,"[Verse 1]\nYeah, people like you, I know myself\nWalk in the shoes of somebody else\nWhisper to me my tragic fate\nWhisper to me my tragic end\n\n[Chorus]\nBut don't give me your savior\nDon't give me your savior\nI said, hey, yeah\n\n[Verse 2]\nYeah, people, I choose life on my own\nBurn me your fuse, throw me your stone\nGive me your brand, burn on my hand\nWhisper to me my tragic end\n\n[Chorus]\nBut don't give me your savior\nNo, don't give me your savior\nI said, hey, yeah\n\n[Instrumental Break]\n\n[Verse 3]\nOh, people I choose, I know myself\nLay my need out, give you my help\nBut you give me your blues and you whisper my fate\nBut don't give me, don't give me, oh, your savior\n\n[Guitar Solo]\n\n[Outro]\nDon't give me, don't give me\nWhisper, hide your face\nCry, hide your faith\nWhisper, hide your face\nCry, hide your faith\nWhisper, hide your face\nCry, hide your faith\nWhisper",Temple of the Dog,Temple of the Dog,1991,A&M Records
89,Four Walled World,"[Verse 1]\nWell, she cries, and she cries\nAll night to the sound of the freeway hum\nAnd she swears she'll be gone when the sun hits the ground\nAnd she ain't comin' back to my cell\nTo my cell, ooh\n\n[Verse 2]\nWell she's tired, and she's tired\nOf this life she's been leadin' too long\nAnd the time turns around through these walls that surround\nTo the chimes of a jailer's song\n\n[Chorus]\nOh, but in my four, yeah, in my four\nIn my four, my four-walled world\nIn my four, yeah, in my four\nIn my four, my four-walled world\n\n[Verse 3]\nYeah, she tries, and she tries\nBut my feet, they just won't leave the ground\nAnd I'm tired, and I'm tired of this prisoner's life\nAnd these chains that drag me down\n\n[Chorus]\nOh, but in my four, in my four\nYeah, in my four, in my four-walled world\nYeah, in my four, oh, in my four\nYeah, in my four, my four-walled world\n\n[Verse 1]\nWell she cries, and she cries\nAll night to the sound of the freeway hum\nAnd she swears she'll be gone when the sun hits the ground\nAnd she ain't, no she ain't comin' back to my cell!\n\n[Bridge]\nNow the sun is low\nAnd these walls try to break my soul\nNow the moon is full\nAnd I won't see nothin' tonight but the tear in her eyes\n\n[Outro]\nIn my four\nYeah, in my four world\nYeah, in my four-walled world\nYeah, in my four, my four, yeah, my four, oh, my four-walled world\nYeah, in my four-walled world, yeah\nIn my four, in my four-walled world, yeah\nIn my four, in my four, in my four-walled world, yeah, yeah\nIn my four-walled world, yeah, yeah, yeah\nOh, in my four, in my four-walled world, yeah\nFour! In my four! In my four-walled world, yeah\nIn my four-walled world, yeah",Temple of the Dog,Temple of the Dog,1991,A&M Records
90,All Night Thing,"[Verse 1]\nShe motioned to me that she wanted to leave\nAnd go somewhere warm where we'd be alone\nHuh, I do not know what's goin' on\nBut I'm guessin', ooh, it's an all-night thing\nYeah, it's an all-night thing\n\n[Chorus]\nIf it's an all-night thing, then nobody's gonna make it end\nAnd if it don't begin, and don't worry that I'll take offense\nIf it's an all-night thing, and we fall like a tear fallin' to the ground\nI'll never come around, and you'll never hear a word from me\nIf it's an all-night thing\n\n[Verse 2]\nWell, I walked along, feelin' at ease\nAnd fallin' like rain, ooh, into her scheme\nAnd she won't let on what that'll be\nYeah, but I'm guessin', ooh, it's an all-night thing\nYeah, well it's an all-night thing\n\n[Chorus]\nIf it's an all-night thing, nobody's gonna make it end\nAnd if it don't begin, a-don't worry that I'll take offense\nYeah, if it's an all-night thing, and we fall like a tear fallin' to the ground\nThen I'll never come around, and you'll never hear a word from me\nIf it's an all night thing, yeah, if it's an all-night thing\nOoh, if it's an all-night thing, yeah, if it's an all-night thing\nMm-mmm",Temple of the Dog,Temple of the Dog,1991,A&M Records

In [5]:
chris_cornell_df_without_labels

,track_title,track_lyrics,album_name,project_name,release_year,label
0,Can’t Change Me,"[Verse 1]\nShe can do anything at all\nHave anything she pleases\nThe power to change what she thinks is wrong\nBut what could she want with me? Yeah\n\n[Pre-Chorus]\nBut wait just one minute here\nI can see that she's trying to read me\n(Suddenly I know)\n\n[Chorus]\nShe's going to change the world\nShe's going to change the world\nShe's going to change the world\nBut she can't change me\nNo, she can't change me\n\n[Verse 2]\nShe has the daylight at her command\nShe gives the night its dreams, yeah\nShe can uncover your darkest fear\nAnd make you forget you feel it\n\n[Pre-Chorus]\nBut wait just one minute more\nI can see that she's trying to free me\n(Suddenly I know)\n\n[Chorus]\nShe's going to change the world (Going to change the world)\nShe's going to change the world (Going to change the world)\nShe's going to change the world (Going to change)\nBut she can't change me\nNo, she can't change me\n\n[Bridge]\nAnd suddenly I can see everything that's wrong with me, yeah\nBut what can I do? I'm the only thing I really have at all\n\n[Instrumental Break]\n\n[Pre-Chorus]\nBut wait, just, one minute here\nI can see that she's trying to need me\n(Suddenly I know)\n\n[Chorus]\nShe's going to change the world (Going to change the world)\nShe's going to change the world (Going to change the world)\nShe's going to change the world (Going to change)\nBut she can't change me\nNo, she can't change me",Euphoria Mourning,Chris Cornell,1999,A&M Records
1,Flutter Girl,"[Verse 1]\nI'm drinking dust with eyes of rust\nTonight my tears might stain your wings\nSo flutter home because you're better off alone than with me\n\n[Verse 2]\nSo hide your face and tie your lace\nAnd butterflies across your cheek\nForget how soon you become a fool for words when I speak\n\n[Chorus]\nFlutter girl\nYou don't want to know what I live\nYou don't want to take what I give\nBecause I give nothing for free\nYou don't want to know what I live\nYou don't want to take what I give\nBecause I give nothing for free\n\n[Verse 3]\nMy hands are rough, my fingers cold\nAnd your heart's so young and so naive\nTo ever feel for a moment that I might dare to believe\n\n[Chorus]\nFlutter girl\nYou don't want to know what I live\nYou don't want to take what I give\nBecause I give nothing for free\nYou don't want to know what I live\nYou don't want to take what I give\nBecause I give nothing for free\n\n[Bridge]\nI'll tear your wings\nAs I melt in your smile\nAs I run all your colors away\n\n[Chorus]\nFlutter girl\nYou don't want to know what I live\nYou don't want to take what I give\nBecause I give nothing for free\nYou don't want to know what I live\nYou don't want to take what I give\nBecause I give nothing for free\n\n[Outro]\nFlutter girl",Euphoria Mourning,Chris Cornell,1999,A&M Records
2,Preaching the End of the World,"[Verse 1]\nHello, I know there's someone out there\nWho can understand and who's feeling the same way as me\nI'm 24 and I've got everything to live for\nBut I know now that it wasn't meant to be\n\n[Verse]\n'Cause all has been lost and all has been won\nAnd there's nothing left for us to save\nBut now I know that I don't wanna be alone today\nSo if you're finding you've been feeling just the same\n\n[Chorus]\nCall me now, it's alright\nIt's just the end of the world\nYou'll need a friend in the world\n'Cause you can't hide\nSo call and I'll get right back\nIf your intentions are pure\nI'm seeking a friend for the end of the world\n\n[Verse]\nI've got a photograph, I'll send it off today\nYou will see that I am perfectly sane\nNot for a lifetime or ""forever and a day""\n'Cause we know now that just won't be the case\n\n[Chorus]\nSo call me now, it's alright\nIt's just the end of the world\nYou'll need a friend in the world\n'Cause you can't hide\nSo call and I'll get right back\nIf your intentions are pure\nI'm seeking a friend for the end of the world\n\n[Bridge]\nWith no commitment and no confessions\nAnd no little secrets to keep\nNo little children or houses with roses\nJust the end of the world and me\n\n[Verse]\n'Cause all has been gone and all has been done\nAnd there's nothing left for us to save\nBut we could be together as they blow it all away\nAnd we could share in every moment as it breaks\n\n[Chorus]\nSo call me now, it's alright\nIt's just the end of the world\nYou'll need a friend in the world\n'Cause you can't hide\nSo call and I'll get right back\nIf your intentions are pure\nI'm seeking a friend for the end of the world\n\n[Chorus]\nSo call me now, it's alright\nIt's just the end of the world\nYou'll need a friend in the world\n'Cause you can't hide\nSo call and I'll get right back\nIf your intentions are pure\nI'm seeking a friend for the end of the world",Euphoria Mourning,Chris Cornell,1999,A&M Records
3,Follow My Way,"[Verse 1]\nLittle one, don't be a fool\nI'm a wreck when I look mighty\nIn euphoria, I'm bruised\nIn confusion, next I'm lightning\nIn complacence, I am small\nThrough oblivion I'm charged\n\n[Chorus]\nFollow my way when I'm not leading anyone\nOpen and frayed when you can see that I'm unsure\nOut on my way, I'm only pure when I get lost\nAnd you're only needing when you're finding that I'm not\n\n[Verse 2]\nYou're just looking for a boy\nBathed in infrared and sunlight\nI'm all polish and reward\nWhen I'm confident, I'm hopeless\nJust like everybody else\nRight before they fall apart\n\n[Chorus]\nSo follow my way when I am falling from your heart\nWhen I'm the pain, fever, and sweet relief in one\nOut on my way, though I'm not worthy of your trust\nFollow me down into a swan dive, all eyes closed tight\n\n[Bridge]\nLowly, slowly, now I know\nI love where you go when you're gone\nWarm your hands inside my veins\nI might be contagious\nThrough oblivion, I charge\n\n[Chorus]\nSo follow my way when I am useless to your cause\nWhen I derail, calm in the patience of remorse\nOut on my way, out on my empty open nerves\nWhen all you know is that I don't know where we are\nWhen all you know is that I don't know\nFollow my way",Euphoria Mourning,Chris Cornell,1999,A&M Records
4,When I’m Down,"[Verse 1]\nWhat say you now\nThe door is opening on your vigil\nNow I'm in my usual way\nI save my breath, knowing what you're\nYou're wanting me to say\nI only love you when I'm down\n\n[Verse 2]\nYou say that midnight opens its arms to me\nLeaving you alone, then I fly so far away\nUntil the light blurs my vision and I have nowhere to roam\nI only love you when I'm down\nOoo\n\n[Chorus]\nAnd I only love you when I'm down\nAnd I'm only near you when I'm gone\nBut one thing for you to keep in mind, you know\nThat I'm down all the time, all the time\n\n[Verse 3]\nWell, I know you're reaching out and you\nYou need to feel my hand\nYou want to be understood\nYeah, well, I understand\nI know you hold precious little hope for me\nAnd in your happiness, I'm always drowning in my grief\n\n[Chorus]\nAnd I only love you when I'm down, oh-oh\nAnd I'm only near you when I'm gone\nBut one thing for you to keep in mind, you know\nThat I'm down all the time, all the time\n\n[Outro]\nAll the time\nAll the time",Euphoria Mourning,Chris Cornell,1999,A&M Records
...,...,...,...,...,...,...
5,Times of Trouble,"[Verse 1]\nWhen the spoon is hot and the needle's sharp\nAnd you drift away, ooh, I can hear you say\nThat the world in black is upon your back\nAnd your body shakes, so you ditch away\nYeah, and you close the shades\n\n[Chorus 1]\nDon't try to do it, don't try to kill your time, oh\nYeah, you might do it, then you can't change your mind, oh-oh, oh-oh-oh\nYou gotta hold onto your time 'til you break through these times of\nTrouble\n\n[Verse 2]\nWhen you try to talk and the words get hard\nAnd they put you down, don't you stay\nMm-mmm, don't ditch away\n\n[Chorus 2]\nI saw you swingin', yeah, swingin' your mother's sword, oh-oh-oh-oh-oh\nAnd yeah, yeah, yeah, I know you're playin', oh, sometimes the rules get hard, oh-oh, oh-oh-oh\nBut if somebody left you out on a ledge\nIf somebody pushed you over the edge\nYou gotta hold on to your time and break through these times of\nTrouble\n\n[Harmonica Solo]\n\n[Chorus 2]\nI saw you swingin', yeah, swingin' your mother's sword, ooh\nAnd yeah, yeah, yeah, I know you're playin', but oh, sometimes the rules get hard, oh-oh-oh-oh-oh\nBut if somebody left you on out on the ledge\nIf somebody pushed you, you're over the edge\nIf somebody loved you and left you for dead\nYou gotta hold on to your time and break through these times of\nTrouble",Temple of the Dog,Temple of the Dog,1991,A&M Records
6,Wooden Jesus,"[Verse 1]\nWooden Jesus, where are you from?\nKorea or Canada or maybe Taiwan?\nBut I didn't know it was the Holy Land\nBut I believed from the minute the check left my hand, I pray\n\n[Chorus]\nCan I be saved?\nI spent all my money on a future grave\nWooden Jesus, I'll cut you in\nOn twenty percent of my future sin\n\n[Post-Chorus]\nI'll cut you in\n\n[Verse 2]\nYeah, Porcelain Mary, her majesties pure\nLooking for virgin territory\nCoat-hanger halos that don't come cheap\nFrom television shepherds with livin' room sheep, and I pray\n\n[Chorus]\nCan I be saved?\nI spent all my money on a future grave\nWooden Jesus, I'll cut you in\nOn twenty percent of my future sin\n\n[Post-Chorus]\nI'll cut you in\nI'll cut you in\n\n[Guitar Solo]\n\n[Bridge]\nHey, Wooden Jesus, where are you from?\nKorea or Canada or maybe Taiwan?\nBut I didn't know it was the Holy Land!\nBut I believed from the minute the check left my hand!\n\n[Chorus]\nOh, can I be saved?\nI spent all my money on a future grave\nWooden Jesus, I'll cut you in\nOn twenty percent of my future sin\n\n[Outro]\nHey!\nI'll cut you in, I'll cut you in\nI'll cut you in, I'll cut you in\nI'll cut you in, I'll cut you in\nYeah\nOoh-ooh-ooh-ooh, ooh",Temple of the Dog,Temple of the Dog,1991,A&M Records
7,Your Saviour,"[Verse 1]\nYeah, people like you, I know myself\nWalk in the shoes of somebody else\nWhisper to me my tragic fate\nWhisper to me my tragic end\n\n[Chorus]\nBut don't give me your savior\nDon't give me your savior\nI said, hey, yeah\n\n[Verse 2]\nYeah, people, I choose life on my own\nBurn me your fuse, throw me your stone\nGive me your brand, burn on my hand\nWhisper to me my tragic end\n\n[Chorus]\nBut don't give me your savior\nNo, don't give me your savior\nI said, hey, yeah\n\n[Instrumental Break]\n\n[Verse 3]\nOh, people I choose, I know myself\nLay my need out, give you my help\nBut you give me your blues and you whisper my fate\nBut don't give me, don't give me, oh, your savior\n\n[Guitar Solo]\n\n[Outro]\nDon't give me, don't give me\nWhisper, hide your face\nCry, hide your faith\nWhisper, hide your face\nCry, hide your faith\nWhisper, hide your face\nCry, hide your faith\nWhisper",Temple of the Dog,Temple of the Dog,1991,A&M Records
8,Four Walled World,"[Verse 1]\nWell, she cries, and she cries\nAll night to the sound of the freeway hum\nAnd she swears she'll be gone when the sun hits the ground\nAnd she ain't comin' back to my cell\nTo my cell, ooh\n\n[Verse 2]\nWell she's tired, and she's tired\nOf this life she's been leadin' too long\nAnd the time turns around through these walls that surround\nTo the chimes of a jailer's song\n\n[Chorus]\nOh, but in my four, yeah, in my four\nIn my four, my four-walled world\nIn my four, yeah, in my four\nIn my four, my four-walled world\n\n[Verse 3]\nYeah, she tries, and she tries\nBut my feet, they just won't leave the ground\nAnd I'm tired, and I'm tired of this prisoner's life\nAnd these chains that drag me down\n\n[Chorus]\nOh, but in my four, in my four\nYeah, in my four, in my four-walled world\nYeah, in my four, oh, in my four\nYeah, in my four, my four-walled world\n\n[Verse 1]\nWell she cries, and she cries\nAll night to the sound of the freeway hum\nAnd she swears she'll be gone when the sun hits the ground\nAnd she ain't, no she ain't comin' back to my cell!\n\n[Bridge]\nNow the sun is low\nAnd these walls try to break my soul\nNow the moon is full\nAnd I won't see nothin' tonight but the tear in her eyes\n\n[Outro]\nIn my four\nYeah, in my four world\nYeah, in my four-walled world\nYeah, in my four, my four, yeah, my four, oh, my four-walled world\nYeah, in my four-walled world, yeah\nIn my four, in my four-walled world, yeah\nIn my four, in my four, in my four-walled world, yeah, yeah\nIn my four-walled world, yeah, yeah, yeah\nOh, in my four, in my four-walled world, yeah\nFour! In my four! In my four-walled world, yeah\nIn my four-walled world, yeah",Temple of the Dog,Temple of the Dog,1991,A&M Records
9,All Night Thing,"[Verse 1]\nShe motioned to me that she wanted to leave\nAnd go somewhere warm where we'd be alone\nHuh, I do not know what's goin' on\nBut I'm guessin', ooh, it's an all-night thing\nYeah, it's an all-night thing\n\n[Chorus]\nIf it's an all-night thing, then nobody's gonna make it end\nAnd if it don't begin, and don't worry that I'll take offense\nIf it's an all-night thing, and we fall like a tear fallin' to the ground\nI'll never come around, and you'll never hear a word from me\nIf it's an all-night thing\n\n[Verse 2]\nWell, I walked along, feelin' at ease\nAnd fallin' like rain, ooh, into her scheme\nAnd she won't let on what that'll be\nYeah, but I'm guessin', ooh, it's an all-night thing\nYeah, well it's an all-night thing\n\n[Chorus]\nIf it's an all-night thing, nobody's gonna make it end\nAnd if it don't begin, a-don't worry that I'll take offense\nYeah, if it's an all-night thing, and we fall like a tear fallin' to the ground\nThen I'll never come around, and you'll never hear a word from me\nIf it's an all night thing, yeah, if it's an all-night thing\nOoh, if it's an all-night thing, yeah, if it's an all-night thing\nMm-mmm",Temple of the Dog,Temple of the Dog,1991,A&M Records

In [6]:
#Keep lyric tags but remove line breaks. See what the analysis is like with and without these tags 

chris_cornell_df_without_labels['track_lyrics'] = chris_cornell_df_without_labels['track_lyrics'].str.replace('\n', ' ')

In [7]:
#!pip install -U spacy

In [8]:
#fromchatgpt. couldn't figure out how to download en_core_web_sm when error said spacy module wasn't found 

import sys
!{sys.executable} -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.8.0
  Downloading en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 36.2 MB/s  0:00:00.9 MB/s eta 0:00:01
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

In [9]:
# Intro to spacy: https://www.youtube.com/watch?v=8vAq-SSnMsM

In [10]:
import spacy
nlp = spacy.load('en_core_web_sm')

In [11]:
# Source - https://stackoverflow.com/a/51627002
# Posted by Romain, modified by community. See post 'Timeline' for change history
# Retrieved 2026-07-10, License - CC BY-SA 4.0

print(nlp.Defaults.stop_words)

{'could', 'ours', 'be', 'above', 'would', 'with', 'throughout', 'during', 'thereupon', 'herein', 'former', 'they', 'while', '’re', 'whose', 'hereupon', 'among', 'again', 'whence', 'done', 'four', 'together', 'bottom', 'give', 'through', 'really', "'m", '‘ll', 'latterly', 'sometime', 'afterwards', 'however', 'over', 'thereafter', 'whoever', 'ever', 'an', 'first', 'until', 'whatever', 'and', 'third', 'otherwise', 'around', 'by', 'without', 'well', 'those', 'toward', 'say', 'three', 'here', 'hence', 'always', 'rather', '’ll', 'less', 'itself', 'besides', 'everything', 'or', 'much', 'moreover', 'no', 'latter', 'show', 'had', 'used', 'i', "'ll", 'than', 'quite', 'thru', 'just', 'became', 'mostly', 'front', 'out', 'which', 'if', 'go', 'put', 'even', 'into', 'still', 'can', 'onto', 'either', 'everyone', 'top', 'yourself', 'nobody', 'somewhere', 'also', 'elsewhere', 'to', 'every', 'too', 'formerly', 'eight', 'nowhere', 'eleven', 'hereby', 'was', 'your', 'should', 'were', 'did', 'me', 'we', 'therein', 'the', 'themselves', 'five', 'already', 'whenever', 'as', 'forty', 'often', 'on', 'then', 'her', 'upon', '‘s', '‘re', 'each', 'get', 'due', 'seemed', 'full', 'you', "'d", 'hundred', 'herself', 'hereafter', 'various', 'someone', 'how', 'via', 'any', 'whom', 'ca', 'please', 'though', 'anything', 'none', 'seem', 'becomes', 'have', 'when', 'after', 'these', 'side', 'will', "'re", 'other', 'been', 'made', 'of', '‘ve', 'seems', 'same', 'twenty', "'ve", 'hers', 'others', 'twelve', 'nine', 'except', 'that', 'between', 'whereas', 'amount', 'further', 'within', 'nevertheless', 'it', 'beforehand', 'regarding', "n't", 'not', 'noone', 'what', 'whereupon', 'see', 'because', 'might', 'down', 'a', 'beyond', 'about', 'towards', 'wherever', 'doing', 're', 'my', 'beside', 'am', 'per', 'this', 'once', 'becoming', 'whereafter', 'therefore', 'namely', 'yours', 'amongst', 'does', 'very', 'seeming', 'neither', 'take', 'he', 'make', 'meanwhile', 'using', 'fifty', 'enough', '’d', 'alone', 'nor', 'empty', 'being', 'them', 'at', 'several', 'few', 'now', 'has', 'two', 'sometimes', 'anyhow', 'never', 'all', 'both', 'for', 'thus', 'keep', 'along', 'such', 'whither', 'himself', 'most', 'its', 'off', 'before', 'last', 'from', 'so', 'do', 'in', 'yet', 'one', 'six', '’s', 'why', '’ve', 'below', 'but', 'ten', 'anywhere', 'call', 'else', 'back', 'may', 'yourselves', 'anyway', 'next', 'cannot', 'move', 'another', 'somehow', 'where', 'us', 'fifteen', 'anyone', 'everywhere', 'become', 'there', 'many', 'myself', 'unless', '‘d', 'are', 'behind', 'thence', 'serious', 'n’t', 'his', 'is', 'own', 'mine', 'since', 'him', 'she', 'some', 'only', 'who', 'part', 'whole', '‘m', 'whereby', 'thereby', 'their', 'perhaps', 'least', 'something', 'almost', 'up', 'whether', 'wherein', 'although', 'indeed', 'across', 'under', 'ourselves', 'must', 'sixty', '’m', 'nothing', 'n‘t', "'s", 'name', 'our', 'against', 'more'}

In [57]:
#Create new list for processed_track_lyrics 
#Remove some stop words from spacy's default list (mostly pronouns and contractions)
#Cut singing sounds 
#Keep question mark and apostraphes but cut dashes and commas 
#make everything lowercase 

processed_track_lyrics =[]

import string

not_stop_words = ["i", 
                  "'m", 
                  "myself",
                  "she", 
                  "'s", 
                  "he", 
                  "'s",
                  "hers",
                  "her",
                  "his",
                  "that",
                  "you", 
                  "yourself",
                  "yourselves",
                  "herself",
                  "himself",
                  "me", 
                  "us", 
                  "we", 
                  "'re", 
                  "our", 
                  "ours", 
                  "they", 
                  "'re",
                  "won't",
                 "world",
                 "woman",
                 "man",
                 "ca",
                  "does",
                 "n't",
                 "was",
                 "do",
                 "did",
                 "would",
                 "was",
                 "ain't",
                 "it",
                 "never",
                 "not",
                 "none",
                 "no"]

added_stop_words = ["verse",
                "1",
                "2",
                "3",
                "4",
                "outro",
                "bridge",
                "chorus",
                "post",
                "pre",
                "chris",
                "cornell",
                "eddie",
                "vedder",
                "guitar",
                "solo",
                "hook",
                "vocal",
                "ad-libs",
                "interlude",
                "instrumental",
                "intro",
                "prechorus",
                "postchorus",
                "ad",
                "libs"]

sing_sounds = ["ooh",
           "oh",
           "ohohohohoh",
           "ohohohohoh",
           "mmmmm",
           "mm",
           "mmm",
           "hey",
           "heyyyy",
           "la",
           "yeah",
            "heyyyy-ya-la-la-hey-hey",
            "oh",
            "oh-oh-oh-oh-oh",
            "ooo",
            "oh-oh",
            "ooh-ooh-ooh-ooh",
            "ooh",
            "oohoohoohooh",
            "ohoh",
            "ohohoh",
            'ohooh',
            "oohooh",
            "uh",
            "huh",
            "heyyyyyalalaheyhey",
            "a-say",
            "a-",
            "adlibs",
            "asay",
            "ah",
            "yeahyeah",
            "oh-woah",
            "whoo",
            "oh-ooh-ooh-ooh-ooh",
            "ohoohoohoohooh",
            "ahahahohoh",
            "ah-ah-ah-oh-oh",
            "a-yeah",
            "ayeah",
            "huah"] 

punctuation = string.punctuation.replace("?", "").replace("'", "")

for word in not_stop_words:
     nlp.vocab[word].is_stop = False

for word in added_stop_words:
    nlp.vocab[word].is_stop = True

for index in range(len(chris_cornell_df_without_labels)):
    text = chris_cornell_df_without_labels.iloc[index]["track_lyrics"].lower().strip()
    text = " ".join(text.split())
    text = text.replace("adon't", "don't")
    text = text.replace("a-don't", "don't")
    text = text.replace('"think it\'s on d"', '')
    text = text.replace('i think so"', '')
    text = text.replace('"i just hit the wrong chord"', '')
    text = text.replace("…", "")
    non_punctuation = "".join(ch for ch in text if ch not in punctuation)

    doc=nlp(non_punctuation)

    processed_text = " ".join(token.text for token in doc if not token.is_stop and token.text not in sing_sounds)
    processed_text = processed_text.replace(" '", "'")
    processed_text = processed_text.replace("wo n't", "won't")
    processed_text = processed_text.replace("ca n't", "can't")
    processed_text = processed_text.replace("do n't", "don't")
    processed_text = processed_text.replace("did n't", "didn't")
    processed_text = processed_text.replace("for 's", "for's")
    processed_text = processed_text.replace("it 's", "it's")
    processed_text = processed_text.replace("was 't", "wasn't")
    processed_text = processed_text.replace("is n't", "isn't")
    processed_text = processed_text.replace("would n't", "wouldn't")
    processed_text = processed_text.replace("ai n't", "ain't")
    processed_text = processed_text.replace("got ta", "gotta")
    processed_text = processed_text.replace("gon na", "gonna")
    processed_text = processed_text.replace("afrom", "from")
    processed_text = processed_text.replace("adon't", "don't")
    processed_text = processed_text.replace("a-don't", "don't")
    processed_text = processed_text.replace("does n't", "doesn't")
    processed_text = processed_text.replace("uhbeautiful", "beautiful")

    processed_track_lyrics.append(processed_text)

#https://www.geeksforgeeks.org/nlp/stop-words-using-spacy/
#https://stackoverflow.com/questions/6142915/remove-unwanted-space-in-between-a-string
#https://www.geeksforgeeks.org/python/string-punctuation-in-python/
#https://stackoverflow.com/questions/41170726/add-remove-custom-stop-words-with-spacy

In [13]:
print(len(processed_track_lyrics))

print(len(chris_cornell_df_without_labels))

91
91

In [56]:
chris_cornell_df_without_labels['processed_track_lyrics']=processed_track_lyrics

In [36]:
print(chris_cornell_df_without_labels.columns)

Index(['track_title', 'track_lyrics', 'album_name', 'project_name',
       'release_year', 'label', 'processed_track_lyrics'],
      dtype='str')